#+TITLE: Objective
#+CATAGORIES: Goal
#+TAGS: Statement
#+WEIGHT: 10
* Objective

Make Common Lisp software easier to use by newbies, and help others customize shared object use in Lisp program delivery.

* Shared Objects to C/C++ routines

These are the .so, .dll, and .mylib files representing functions and data in C/C++.
These C/C++ libraries are required by many common lisp systems available on quicklisp.

* Method to Objective

Convince others to create an easy customization method to find shared object files.


* CL+SSL is the model 

The system CL+SSL allows the programmer to customize the location of required shared object files.

* Workable on Windows

The CL+SSL/config system works for me on Windows.
It is so simple it is likely workable for most external library interfaces to C/C++ libraries.
* The Programmer makes the decision

This is about giving the programmer the OPTION to select the external C/C++ rather than letting the OS make that choice,
and correcting when the OS makes the wrong choice.

